### ISSUE TITLE
Fulfil the GitHub Community checklist

### ISSUE THREAD

**Issue by benHeid** [KIT-IAI/pyWATTS#13]
**Problem**

Currently, we do not have fulfilled all points from the GitHub community checklist. However, this would be very useful. see [Checklist](https://github.com/KIT-IAI/pyWATTS/community) 

**Solution**
* [x] Add PR Template
* [x] Add contributing guideline
* [x] Add Code of Conduct

**Comment by benHeid** [comment]
#53

**Comment by benHeid** [comment]
#72
